# Generated by Django 4.2.3 on 2023-07-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coinstock",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("_1h_percent", models.CharField(max_length=100)),
                ("_24h_percent", models.CharField(max_length=100)),
                ("_7d_percent", models.CharField(default="NULL", max_length=100)),
                ("market_cap", models.CharField(max_length=100)),
                ("volume_24h", models.CharField(max_length=100)),
                ("circulating_supply", models.CharField(max_length=100)),
            ],
        ),
    ]
